### ISSUE TITLE
Google drive 401 error when attempting to create new form or update existing one

### ISSUE THREAD

**Issue by lognaturel** [UDub-Impact/ODK-form-updater#3]
I have tried a few different projects now and always get the same error:

<img width="694" alt="Screen Shot 2023-05-15 at 10 25 53 PM" src="https://github.com/UDub-Impact/ODK-form-updater/assets/967540/ab8a6f8b-221a-465e-932e-a859b3cef1f4">

Some ideas to look into:
- Maybe the request URL isn't structured as expected: https://stackoverflow.com/questions/58503256/request-failed-for-https-docs-google-com-returned-code-401-saving-and-emaili
- Maybe the requested scopes aren't actually sufficient: https://stackoverflow.com/questions/51990923/google-apps-script-urlfetchapp-returning-unauthorized-error-401
- Maybe it's related to oauth

**Comment by lognaturel** [comment]
I was able to get it to work by adding `https://www.googleapis.com/auth/drive.readonly`. My guess is that @WeiJun428 your script cached that scope for some time.

Hopefully there is a narrower scope than reading all Drive documents, though!

**Comment by lognaturel** [comment]
I think `https://www.googleapis.com/auth/drive.file` is ok!

**Comment by WeiJun428** [comment]
@lognaturel Great! Would you recommend using `readonly` or `file`?

**Comment by lognaturel** [comment]
`readonly` is to read every single file in the user's Drive which is quite scary. I thought it was necessary but I think `file` works and is the narrowest possible.

**Comment by WeiJun428** [comment]
We will just go with `drive.file` for now!
